[tool.poetry]
name = "stablepy"
version = "0.1.0"
description = ""
authors = ["Roger Condori <114810545+R3gm@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
omegaconf = "2.3.0"
torch = "^2.0.0"
diffusers = {git = "https://github.com/huggingface/diffusers.git"}
compel = {git = "https://github.com/damian0815/compel.git"}
invisible-watermark = "^0.2.0"
transformers = "^4.34.0"
accelerate = "^0.23.0"
safetensors = "0.3.3"
mediapy = "^1.1.9"
ipywidgets = "7.7.1"
controlnet-aux = "0.0.6"
mediapipe = "0.10.1"
pytorch-lightning = "^2.0.9.post0"
asdff = {git = "https://github.com/R3gm/asdff.git"}
cuda-python = "12.1.0"
nvidia-cusolver-cu12 = "11.4.5.107"
nvidia-cusparse-cu12 = "12.1.0.106"
nvidia-nccl-cu12 = "2.18.1"
triton = "2.1.0"
nvidia-cuda-runtime-cu12 = "12.1.105"
nvidia-cudnn-cu12 = "8.9.2.26"
nvidia-cuda-cupti-cu12 = "12.1.105"
nvidia-curand-cu12 = "10.3.2.106"
nvidia-cufft-cu12 = "11.0.2.54"
nvidia-nvtx-cu12 = "12.1.105"
nvidia-cuda-nvrtc-cu12 = "12.1.105"
nvidia-nvjitlink-cu12 = "^12.2.140"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
